# Generated by Django 6.1 on 2026-08-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_invoicelineitem_packinglistref'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='rateQuote',
            field=models.CharField(choices=[('multiply', '1 source × rate = target'), ('divide', '1 target = rate × source')], default='multiply', max_length=16),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sourceCurrency',
            field=models.CharField(blank=True, default='BDT', max_length=8),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='cbmPerCtn',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='colorSizeNote',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='ctnHeightCm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='ctnLengthCm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='ctnWidthCm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='grossWeightPerCtn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='hsCode',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='markRef',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='netWeightPerCtn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
