# Generated by Django 6.1 on 2026-08-16 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_invoicelineitem_patternno'),
        ('warehouse', '0002_rework_warehouse_cost_scoping'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='warehouseCost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoiceLineItems', to='warehouse.warehousecost'),
        ),
    ]
