# Generated by Django 6.1 on 2026-08-12 16:57

import django.db.models.deletion
import qc.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sourcing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QCReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('reportId', models.CharField(default=qc.models._generate_qc_report_id, max_length=32, unique=True)),
                ('lunchCostFlag', models.BooleanField(default=False)),
                ('lunchCost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('goodsCarryingCost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('travelMode', models.CharField(choices=[('TRAVELLING_WITH_GOODS', 'Travelling with goods'), ('TRAVELLING_INDIVIDUALLY', 'Travelling individually')], default='TRAVELLING_WITH_GOODS', max_length=32)),
                ('extraCost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qcReports', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qcReport', to='sourcing.sourcingrequest')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
