# Generated by Django 6.1 on 2026-08-12 16:57

import core.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('productName', models.CharField(max_length=255)),
                ('photoUrl', models.CharField(blank=True, default='', max_length=1024)),
                ('packingListNotes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING_ADMIN_APPROVAL', 'Pending Approval'), ('APPROVED_FOR_QC', 'Approved for QC'), ('REJECTED', 'Rejected')], default='PENDING_ADMIN_APPROVAL', max_length=32)),
                ('rejectionReason', models.TextField(blank=True, default='')),
                ('reviewedAt', models.DateTimeField(blank=True, null=True)),
                ('brandName', models.CharField(blank=True, default='NA', max_length=255)),
                ('styleNumber', models.CharField(default=core.utils.generate_style_number, max_length=64, unique=True)),
                ('goodsName', models.CharField(blank=True, default='', max_length=255)),
                ('fabricDetails', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('productQrGenerated', models.BooleanField(default=False)),
                ('cartonQrGenerated', models.BooleanField(default=False)),
                ('imageUrls', models.TextField(blank=True, default='[]')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdRequests', to=settings.AUTH_USER_MODEL)),
                ('reviewedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewedRequests', to=settings.AUTH_USER_MODEL)),
                ('sisterProfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcingRequests', to='buyers.sisterprofile')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='SourcingVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('styleNo', models.CharField(blank=True, default='', max_length=255)),
                ('buyer', models.CharField(blank=True, default='', max_length=255)),
                ('poNo', models.CharField(blank=True, default='', max_length=255)),
                ('color', models.CharField(blank=True, default='', max_length=255)),
                ('itemNumber', models.CharField(blank=True, default='', max_length=255)),
                ('size', models.CharField(blank=True, default='', max_length=64)),
                ('qtyOrdered', models.PositiveIntegerField(default=0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='sourcing.sourcingrequest')),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
    ]
