# Generated by Django 6.1 on 2026-08-12 16:57

import django.db.models.deletion
import invoicing.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
        ('sourcing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sourceCurrency', models.CharField(max_length=8)),
                ('targetCurrency', models.CharField(max_length=8)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=14)),
                ('effectiveDate', models.DateTimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('publishedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchangeRates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effectiveDate'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('invoiceNo', models.CharField(default=invoicing.models._generate_invoice_number, max_length=32, unique=True)),
                ('buyerName', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('ISSUED', 'Issued'), ('REJECTED', 'Rejected'), ('VOID', 'Void')], default='PENDING_APPROVAL', max_length=20)),
                ('rejectionReason', models.TextField(blank=True, default='')),
                ('exchangeRateValue', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('targetCurrency', models.CharField(blank=True, default='', max_length=8)),
                ('commissionType', models.CharField(choices=[('NONE', 'None'), ('PERCENTAGE', 'Percentage'), ('FLAT', 'Flat')], default='NONE', max_length=16)),
                ('commissionValue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('totalValue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('convertedTotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outstandingBalance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('approvedAt', models.DateTimeField(blank=True, null=True)),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicesApproved', to=settings.AUTH_USER_MODEL)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoicesCreated', to=settings.AUTH_USER_MODEL)),
                ('exchangeRate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoicing.exchangerate')),
                ('sisterProfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='buyers.sisterprofile')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('brand', models.CharField(blank=True, default='', max_length=255)),
                ('ctn', models.PositiveIntegerField(default=0)),
                ('qtyPerCtn', models.PositiveIntegerField(default=0)),
                ('totalQty', models.PositiveIntegerField(default=0)),
                ('unitPrice', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('netWeight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grossWeight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cbm', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('material', models.CharField(blank=True, default='', max_length=255)),
                ('styleItemCode', models.CharField(blank=True, default='', max_length=255)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineItems', to='invoicing.invoice')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoiceLineItems', to='sourcing.sourcingrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(blank=True, default='USD', max_length=8)),
                ('paymentDate', models.DateTimeField()),
                ('bankReference', models.CharField(blank=True, default='', max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoicing.invoice')),
                ('recordedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paymentDate'],
            },
        ),
    ]
