# Generated by Django 6.1 on 2026-08-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('trip_closed', 'Sourcing Cost Closed'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('invoice_issued', 'Invoice Issued'), ('payment_recorded', 'Payment Recorded'), ('negative_balance_alert', 'Negative Balance Alert'), ('wallet_negative_balance', 'Wallet Negative Balance'), ('wallet_low_balance', 'Wallet Low Balance')], max_length=32),
        ),
    ]
