# Generated by Django 6.1 on 2026-08-12 17:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('contactInfo', models.TextField(blank=True, default='')),
                ('branding', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SisterProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('poReference', models.CharField(blank=True, default='', max_length=255)),
                ('agreementType', models.CharField(choices=[('1', 'Type 1 — % of purchase value'), ('2', 'Type 2 — fixed rate per unit'), ('3', 'Type 3 — reimburse + commission')], max_length=1)),
                ('agreementRateConfig', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('buyerProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sisterProfiles', to='buyers.buyerprofile')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
