# Generated by Django 6.1 on 2026-08-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sisterprofile',
            name='agreementType',
            field=models.CharField(choices=[('1', 'Type 1 — % of sourcing expense'), ('2', 'Type 2 — fixed rate per unit'), ('3', 'Type 3 — reimburse + commission')], max_length=1),
        ),
    ]
