# Generated by Django 6.1 on 2026-08-15 07:03

import apps.buyers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0004_backfill_reference_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='referenceCode',
            field=models.CharField(default=apps.buyers.models.generate_buyer_reference_code, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='sisterprofile',
            name='referenceCode',
            field=models.CharField(default=apps.buyers.models.generate_sister_profile_reference_code, max_length=32, unique=True),
        ),
    ]
