# Generated by Django 6.1 on 2026-08-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0005_alter_buyerprofile_referencecode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sisterprofile',
            name='agreementRateConfig',
        ),
        migrations.AddField(
            model_name='sisterprofile',
            name='buyerCurrency',
            field=models.CharField(default='USD', max_length=8),
        ),
        migrations.AddField(
            model_name='sisterprofile',
            name='exchangeRate',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='sisterprofile',
            name='supplierCurrency',
            field=models.CharField(default='BDT', max_length=8),
        ),
    ]
