# Generated by Django 6.1 on 2026-08-15 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.PositiveSmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('tagline', models.CharField(blank=True, default='', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('addressLine', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('registrationNo', models.CharField(blank=True, default='', max_length=64)),
                ('bankName', models.CharField(blank=True, default='', max_length=255)),
                ('bankAccountTitle', models.CharField(blank=True, default='', max_length=255)),
                ('bankAccountNo', models.CharField(blank=True, default='', max_length=64)),
                ('bankSwiftCode', models.CharField(blank=True, default='', max_length=32)),
                ('bankAddress', models.TextField(blank=True, default='')),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyProfileEdits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company profile',
                'verbose_name_plural': 'Company profile',
            },
        ),
    ]
