# Generated by Django 6.1 on 2026-08-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companyprofile_contactperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='contactPerson',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
