# Generated by Django 6.1 on 2026-08-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_companyprofile_contactperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='sealSignature',
            field=models.ImageField(blank=True, null=True, upload_to='company/'),
        ),
    ]
