# Generated by Django 6.1 on 2026-08-12 17:55

import apps.sourcing.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('styleNumber', models.CharField(default=apps.sourcing.models.generate_style_number, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('brandName', models.CharField(blank=True, default='NA', max_length=255)),
                ('poNo', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('sourcing_trip_open', 'Sourcing Trip Open'), ('pending_admin_approval', 'Pending Admin Approval'), ('rejected', 'Rejected'), ('approved_for_qc', 'Approved for QC'), ('in_warehouse', 'In Warehouse'), ('ready_for_final_qc', 'Ready for Final QC'), ('completed', 'Completed')], default='sourcing_trip_open', max_length=32)),
                ('rejectionReason', models.TextField(blank=True, default='')),
                ('goodsName', models.CharField(blank=True, default='', max_length=255)),
                ('finalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fabricDetails', models.TextField(blank=True, default='')),
                ('factoryPackingList', models.FileField(blank=True, null=True, upload_to='factory_packing_lists/%Y/%m/')),
                ('productQrGenerated', models.BooleanField(default=False)),
                ('cartonQrGenerated', models.BooleanField(default=False)),
                ('reviewedAt', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='createdProducts', to=settings.AUTH_USER_MODEL)),
                ('reviewedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewedProducts', to=settings.AUTH_USER_MODEL)),
                ('sisterProfile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='buyers.sisterprofile')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='product_photos/%Y/%m/')),
                ('label', models.CharField(choices=[('front_label', 'Front Label'), ('back_label', 'Back Label'), ('product_overall', 'Product Overall'), ('fabric_closeup', 'Fabric Close-up'), ('custom', 'Custom')], default='product_overall', max_length=32)),
                ('customLabelName', models.CharField(blank=True, default='', max_length=100)),
                ('gpsLat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gpsLng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('capturedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sourcing.product')),
                ('uploadedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploadedProductImages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(max_length=100)),
                ('patternNo', models.CharField(blank=True, default='', max_length=100)),
                ('itemNbr', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.CharField(max_length=32)),
                ('qtyOrdered', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='sourcing.product')),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='SourcingTrip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=16)),
                ('fullPaymentConfirmedAt', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcingTrips', to='sourcing.product')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='SourcingLocationEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('locationName', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('advanceAmount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reported', 'Reported')], default='pending', max_length=16)),
                ('date', models.DateTimeField()),
                ('reportedAt', models.DateTimeField(blank=True, null=True)),
                ('sourcingTrip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='sourcing.sourcingtrip')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
