# Generated by Django 6.1 on 2026-08-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0005_convert_size_breakdown_to_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sizeBreakdown',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
