# Generated by Django 6.1 on 2026-08-15 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0006_alter_productvariant_sizebreakdown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='customFields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='resolvedTemplateFields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('isActive', models.BooleanField(default=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productTemplates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='sourcing.producttemplate'),
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fieldKey', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('fieldType', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('select', 'Select')], default='text', max_length=16)),
                ('selectOptions', models.JSONField(blank=True, default=list)),
                ('isRequired', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('fieldGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='sourcing.fieldgroup')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='ProductTemplateField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('displayOrder', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templateFields', to='sourcing.producttemplate')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productTemplateFields', to='sourcing.templatefield')),
            ],
            options={
                'ordering': ['displayOrder'],
            },
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='fields',
            field=models.ManyToManyField(related_name='templates', through='sourcing.ProductTemplateField', to='sourcing.templatefield'),
        ),
        migrations.AddConstraint(
            model_name='producttemplatefield',
            constraint=models.UniqueConstraint(fields=('template', 'field'), name='unique_template_field'),
        ),
    ]
