# Generated by Django 6.1 on 2026-08-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0014_remove_sourcinglocationentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('sourcing_trip_open', 'Sourcing Cost Open'), ('pending_admin_approval', 'Pending Admin Approval'), ('rejected', 'Rejected'), ('approved_for_qc', 'Approved for QC'), ('in_warehouse', 'In Warehouse'), ('ready_for_final_qc', 'Ready for Final QC'), ('completed', 'Completed')], default='sourcing_trip_open', max_length=32),
        ),
    ]
