# Generated by Django 6.1 on 2026-08-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_warehousecost'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amountInBuyerCurrency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='expense',
            name='buyerCurrency',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='expense',
            name='exchangeRateUsed',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
    ]
