# Generated by Django 6.1 on 2026-08-12 16:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('contactInfo', models.TextField(blank=True, default='')),
                ('branding', models.CharField(blank=True, default='', max_length=255)),
                ('portalUsername', models.CharField(max_length=150, unique=True)),
                ('portalPasswordHash', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SisterProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('poReference', models.CharField(blank=True, default='', max_length=255)),
                ('agreementType', models.CharField(choices=[('TYPE_1', 'Type 1 (% Commission)'), ('TYPE_2', 'Type 2 (Per Unit)'), ('TYPE_3', 'Type 3 (Reimburse + Commission)')], default='TYPE_1', max_length=16)),
                ('negotiatedRate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('terms', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
                ('buyerProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sisterProfiles', to='buyers.buyerprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
