# Generated by Django 6.1 on 2026-08-12 16:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('loaderCost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('extraWorkerCost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('labelsCost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('htakeCost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stickersCost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cartonsCost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('polyBagsCost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gamtapeCost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customCosts', models.TextField(blank=True, default='[]')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouseCosts', to=settings.AUTH_USER_MODEL)),
                ('qcReport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warehouseCost', to='qc.qcreport')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
