# Generated by Django 6.1 on 2026-08-12 16:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('productId', models.CharField(blank=True, max_length=64, null=True)),
                ('sourceType', models.CharField(choices=[('sourcing_advance', 'Sourcing Advance'), ('qc_lunch', 'QC Lunch'), ('qc_carrying', 'QC Carrying'), ('qc_travel_extra', 'QC Travel Extra'), ('warehouse_loader', 'Warehouse Loader'), ('warehouse_extra_worker', 'Warehouse Extra Worker'), ('warehouse_packaging_item', 'Packaging Item'), ('custom_field', 'Custom Field'), ('extra_cost', 'Extra Cost')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='BDT', max_length=8)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('fieldName', models.CharField(blank=True, max_length=64, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
                ('sisterProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_set', to='buyers.sisterprofile')),
            ],
            options={
                'ordering': ['-createdAt'],
                'indexes': [models.Index(fields=['sisterProfile', 'sourceType'], name='expenses_ex_sisterP_e95742_idx')],
            },
        ),
    ]
