# Generated by Django 6.1 on 2026-08-12 16:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sourcing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('orderQty', models.PositiveIntegerField(default=0)),
                ('shipmentQty', models.PositiveIntegerField(default=0)),
                ('shortQty', models.IntegerField(default=0)),
                ('shortPct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('totalCbm', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('totalNetWeight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('totalGrossWeight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frontMark', models.CharField(blank=True, default='', max_length=255)),
                ('sideMark', models.CharField(blank=True, default='', max_length=255)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packingList', to='sourcing.sourcingrequest')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='PackingCarton',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cartonNoFrom', models.PositiveIntegerField(default=0)),
                ('cartonNoTo', models.PositiveIntegerField(default=0)),
                ('noOfCartons', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(blank=True, default='', max_length=255)),
                ('assortId', models.CharField(blank=True, default='', max_length=255)),
                ('itemNumber', models.CharField(blank=True, default='', max_length=255)),
                ('sizeBreakdown', models.CharField(blank=True, default='', max_length=255)),
                ('qtyPerCarton', models.PositiveIntegerField(default=0)),
                ('shipQty', models.IntegerField(default=0)),
                ('orderQty', models.IntegerField(default=0)),
                ('shortQty', models.IntegerField(default=0)),
                ('shortPct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ctnLength', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ctnWidth', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ctnHeight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('netWeight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grossWeight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ctnCbm', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('packingList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartons', to='packing.packinglist')),
            ],
            options={
                'ordering': ['cartonNoFrom'],
            },
        ),
    ]
