# Generated by Django 6.1 on 2026-08-12 19:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
                ('entityType', models.CharField(max_length=64)),
                ('entityId', models.CharField(max_length=64)),
                ('beforeSnapshot', models.JSONField(blank=True, default=dict)),
                ('afterSnapshot', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditLogEntries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entityType', 'entityId'], name='audit_audit_entityT_8030bb_idx'), models.Index(fields=['actor'], name='audit_audit_actor_i_f4501b_idx')],
            },
        ),
    ]
