# Generated by Django 6.1 on 2026-08-12 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementLedger',
            fields=[
                ('sisterProfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settlementLedger', serialize=False, to='buyers.sisterprofile')),
                ('totalAdvance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('totalExpense', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amountOwed', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('netPosition', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('negativeBalance', models.BooleanField(default=False)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
