# Generated by Django 6.1 on 2026-08-15 06:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0002_alter_sisterprofile_agreementtype'),
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerWallet',
            fields=[
                ('buyerProfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wallet', serialize=False, to='buyers.buyerprofile')),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('lowBalanceThreshold', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('negativeBalance', models.BooleanField(default=False)),
                ('lowBalance', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('top_up', 'Top-up'), ('deduction', 'Deduction'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('exchangeRateUsed', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('sourceType', models.CharField(blank=True, default='', max_length=32)),
                ('methodReference', models.CharField(blank=True, default='', max_length=255)),
                ('reason', models.TextField(blank=True, default='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='walletTransactions', to=settings.AUTH_USER_MODEL)),
                ('sisterProfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walletTransactions', to='buyers.sisterprofile')),
                ('sourceExpense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walletTransactions', to='expenses.expense')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.buyerwallet')),
            ],
            options={
                'ordering': ['-createdAt'],
                'indexes': [models.Index(fields=['wallet', 'createdAt'], name='wallet_wall_wallet__74922f_idx')],
            },
        ),
    ]
