# Generated by Django 6.1 on 2026-08-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_backfill_wallets'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='sourceAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='sourceCurrency',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
