# Generated by Django 6.1 on 2026-08-12 19:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVaultItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documentType', models.CharField(choices=[('po', 'Purchase Order'), ('contract', 'Contract'), ('invoice', 'Invoice'), ('packing_list', 'Packing List'), ('qc_photo', 'QC Photo'), ('other', 'Other')], default='other', max_length=16)),
                ('file', models.FileField(upload_to='document_vault/%Y/%m/')),
                ('fileName', models.CharField(blank=True, default='', max_length=255)),
                ('fileSize', models.PositiveIntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('sisterProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='buyers.sisterprofile')),
                ('uploadedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploadedDocuments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
