# Generated by Django 6.1 on 2026-08-12 16:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sourcing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcingTrip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('totalAdvance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closedAt', models.DateTimeField(blank=True, null=True)),
                ('closedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closedTrips', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcingTrips', to='sourcing.sourcingrequest')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='TripLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('locationName', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('advanceAmount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REPORTED', 'Reported')], default='PENDING', max_length=16)),
                ('date', models.DateTimeField()),
                ('sourcingTrip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='trips.sourcingtrip')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
