# Generated by Django 6.1 on 2026-08-12 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
        ('sourcing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('poNo', models.CharField(blank=True, default='', max_length=255)),
                ('brandName', models.CharField(blank=True, default='', max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('frontMark', models.TextField(blank=True, default='')),
                ('sideMark', models.TextField(blank=True, default='')),
                ('totalOrderQty', models.PositiveIntegerField(default=0)),
                ('totalShipQty', models.PositiveIntegerField(default=0)),
                ('shortExcessQty', models.IntegerField(default=0)),
                ('shortExcessPct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('totalCartonQty', models.PositiveIntegerField(default=0)),
                ('totalGrossWeight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('totalNetWeight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('totalCbm', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packingLists', to=settings.AUTH_USER_MODEL)),
                ('sisterProfile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packingLists', to='buyers.sisterprofile')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='PackingCarton',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cartonNoFrom', models.PositiveIntegerField()),
                ('cartonNoTo', models.PositiveIntegerField()),
                ('noOfCartons', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(max_length=100)),
                ('patternNo', models.CharField(blank=True, default='', max_length=100)),
                ('assortId', models.CharField(blank=True, default='', max_length=100)),
                ('sizeBreakdown', models.JSONField(default=dict)),
                ('totalPcsPerCarton', models.PositiveIntegerField(default=0)),
                ('innerBundle', models.PositiveIntegerField(default=1)),
                ('orderQty', models.PositiveIntegerField(default=0)),
                ('shipQty', models.PositiveIntegerField(default=0)),
                ('shortExcessQty', models.IntegerField(default=0)),
                ('shortExcessPct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('grossWeight', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('netWeight', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('totalGrossWeight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('totalNetWeight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ctnLength', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ctnWidth', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ctnHeight', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ctnCbm', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('totalCbm', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packingCartons', to='sourcing.product')),
                ('packingList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartons', to='packing.packinglist')),
            ],
            options={
                'ordering': ['cartonNoFrom'],
            },
        ),
        migrations.CreateModel(
            name='PackingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('sizeRatio', models.JSONField(default=dict)),
                ('cartonLength', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cartonWidth', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cartonHeight', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cartonNetWeight', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cartonGrossWeight', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('buyerProfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packingRules', to='buyers.buyerprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='packinglist',
            name='packingRule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packingLists', to='packing.packingrule'),
        ),
    ]
