# Generated by Django 6.1 on 2026-08-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0004_convert_size_breakdown_to_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingcarton',
            name='sizeBreakdown',
            field=models.JSONField(default=list),
        ),
    ]
