# Generated by Django 6.1 on 2026-08-12 18:28

import apps.qc.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sourcing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QCReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('reportId', models.CharField(default=apps.qc.models._generate_qc_report_id, max_length=32, unique=True)),
                ('lunchCostFlag', models.BooleanField(default=False)),
                ('lunchCost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('goodsCarryingCost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('travelMode', models.CharField(choices=[('travelling_with_goods', 'Travelling with Goods'), ('travelling_individually', 'Travelling Individually')], default='travelling_with_goods', max_length=32)),
                ('extraCost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qcReports', to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='qcReport', to='sourcing.product')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
